### ISSUE TITLE
Scan file is locked by multianalyzer

### ISSUE THREAD

**Issue by woutdenolf** [kif/multianalyzer#11]
To be used online, this code should never lock the file and should retry in case of failure (concurrent read/write).

I could do one of these things:

1. use the h5py utils from silx in multianalyzer
2. or do the hdf5 reading [outside](https://gitlab.esrf.fr/workflow/ewoksapps/ewoksid22/-/blob/main/ewoksid22/rebin.py) and multianalyzer receives the data in memory

@kif What do you prefer?

**Comment by kif** [comment]
The usage of silx.io is the easiest for now.
Did you have a look at the profiling results? Most of the time is spent in reading and writing HDF5 files.
So memory access would be desirable but the amount of data to share (several GB) makes it impracticable when processing on a different computer. Memcached does not scale well above dozens of MB. So probably going via HDF5 is still the best.
